# Generated by Django 5.2.7 on 2025-10-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('existencias', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['fecha_caducidad', 'numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad_medica', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'numero_lote')},
        ),
    ]
