# Generated by Django 5.2.7 on 2025-11-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento_usuario_alter_movimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
