# Generated by Django 5.2.8 on 2025-11-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='centro',
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lote',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='requisicionitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='requisicionitem',
            name='requisicion',
        ),
        migrations.DeleteModel(
            name='Centro',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Requisicion',
        ),
        migrations.DeleteModel(
            name='RequisicionItem',
        ),
    ]
