# Generated by Django 5.2.8 on 2025-11-13 17:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_autorizada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_surtida', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'detalles_requisicion',
            },
        ),
        migrations.CreateModel(
            name='ImportacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('productos_creados', models.IntegerField(default=0)),
                ('productos_actualizados', models.IntegerField(default=0)),
                ('errores', models.JSONField(default=list)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'importacion_logs',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(help_text='Número de lote único por producto (3-100 caracteres)', max_length=100, validators=[django.core.validators.RegexValidator(message='El número de lote solo puede contener letras, números y guiones', regex='^[A-Za-z0-9\\-]+$')])),
                ('fecha_caducidad', models.DateField(help_text='Fecha de caducidad del lote')),
                ('cantidad_inicial', models.IntegerField(help_text='Cantidad inicial del lote', validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_actual', models.IntegerField(help_text='Cantidad actual disponible', validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado')], default='disponible', help_text='Estado actual del lote', max_length=20)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra del lote', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('factura', models.CharField(blank=True, max_length=100)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lotes',
                'ordering': ['-fecha_entrada', 'fecha_caducidad'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('requisicion', 'Requisición')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave única del producto (3-50 caracteres alfanuméricos)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números, guiones y guiones bajos', regex='^[A-Za-z0-9\\-_]+$')])),
                ('descripcion', models.TextField(help_text='Descripción del producto (5-300 caracteres)')),
                ('unidad_medida', models.CharField(choices=[('PIEZA', 'Pieza'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('SOBRE', 'Sobre'), ('AMPOLLETA', 'Ampolleta'), ('TABLETA', 'Tableta'), ('CAPSULA', 'Cápsula'), ('ML', 'Mililitro'), ('GR', 'Gramo')], help_text='Unidad de medida del producto', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_minimo', models.IntegerField(default=10, help_text='Cantidad mínima en inventario antes de alerta', validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo en el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('autorizada', 'Autorizada'), ('parcial', 'Parcialmente Autorizada'), ('rechazada', 'Rechazada'), ('surtida', 'Surtida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'requisiciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.AddField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('superusuario', 'Superusuario'), ('admin_farmacia', 'Admin Farmacia'), ('usuario_normal', 'Usuario Normal'), ('usuario_vista', 'Usuario Vista')], default='usuario_normal', help_text='Rol del usuario en el sistema', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Tipo de acción: crear, editar, eliminar, autorizar, etc.', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo afectado: Producto, Requisicion, Lote, etc.', max_length=50)),
                ('objeto_id', models.IntegerField(help_text='ID del objeto afectado')),
                ('objeto_repr', models.CharField(help_text='Representación del objeto', max_length=255)),
                ('cambios', models.JSONField(default=dict, help_text='Detalles de los cambios realizados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_logs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')])),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'centros',
                'ordering': ['clave'],
                'indexes': [models.Index(fields=['activo'], name='centros_activo_2ccbbc_idx'), models.Index(fields=['clave'], name='centros_clave_b95aa4_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='centro',
            field=models.ForeignKey(blank=True, help_text='Centro asignado al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.centro'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rol', 'activo'], name='usuarios_rol_5088ae_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['centro', 'activo'], name='usuarios_centro__2bcb92_idx'),
        ),
        migrations.AddField(
            model_name='importacionlog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.centro'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.lote'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(help_text='Producto al que pertenece el lote', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.producto'),
        ),
        migrations.AddField(
            model_name='detallerequisicion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones', to='core.centro'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario_autoriza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario_solicita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='requisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='core.requisicion'),
        ),
        migrations.AddField(
            model_name='detallerequisicion',
            name='requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.requisicion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='centro',
            field=models.ForeignKey(blank=True, help_text='Centro asignado al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_perfil', to='core.centro'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['usuario', '-fecha'], name='auditoria_l_usuario_a06334_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['modelo', 'objeto_id'], name='auditoria_l_modelo_3b0875_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['-fecha'], name='auditoria_l_fecha_31af9d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_activo_aa3d01_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['clave'], name='productos_clave_7898b3_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['unidad_medida'], name='productos_unidad__a4a84b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-created_at'], name='productos_created_1dedc5_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='lotes_estado_a6768b_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_caducidad'], name='lotes_fecha_c_c062b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'estado'], name='lotes_product_882089_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['deleted_at'], name='lotes_deleted_aeb352_idx'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_lote'), name='unique_numero_lote_por_producto'),
        ),
        migrations.AddIndex(
            model_name='requisicion',
            index=models.Index(fields=['estado'], name='requisicion_estado_d992ad_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicion',
            index=models.Index(fields=['centro', 'estado'], name='requisicion_centro__09447f_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicion',
            index=models.Index(fields=['-fecha_solicitud'], name='requisicion_fecha_s_542d51_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo'], name='movimientos_tipo_c3fb35_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['lote', 'tipo'], name='movimientos_lote_id_14ada9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['-fecha'], name='movimientos_fecha_9b7878_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['centro', '-fecha'], name='movimientos_centro__79a0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='detallerequisicion',
            index=models.Index(fields=['requisicion', 'producto'], name='detalles_re_requisi_24622f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallerequisicion',
            unique_together={('requisicion', 'producto')},
        ),
    ]
