# Generated by Django 5.2.8 on 2025-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_importacionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='centro',
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin_sistema', 'Administrador del sistema'), ('farmacia', 'Usuario Farmacia'), ('centro', 'Usuario Centro/Unidad'), ('vista', 'Usuario Vista/Consultor'), ('superusuario', 'Superusuario (legacy)'), ('admin_farmacia', 'Admin Farmacia (legacy)'), ('usuario_normal', 'Usuario Centro (legacy)'), ('usuario_vista', 'Usuario Vista (legacy)')], default='usuario_normal', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
