# Generated by Django 5.2.8 on 2025-11-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etapa2_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras del lote (RFC-45)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras_producto',
            field=models.CharField(blank=True, help_text='Código de barras del producto (opcional)', max_length=50, null=True, unique=True),
        ),
    ]
