# Generated by Django 5.2.8 on 2025-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agregar_codigo_barras'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'estado', 'fecha_caducidad'], name='idx_lote_stock_lookup'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado', 'fecha_caducidad', 'cantidad_actual'], name='idx_lote_disponible'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'stock_minimo'], name='idx_producto_activo_stock'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['clave', 'activo'], name='idx_producto_clave_activo'),
        ),
    ]
