# Generated by Django 4.2.26 on 2025-11-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lote_centro_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='objeto_id',
            field=models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='objeto_repr',
            field=models.CharField(blank=True, default='', help_text='Representación del objeto', max_length=255),
        ),
    ]
