# Generated by Django 5.2.8 on 2025-12-01 - Etapa 3 nuevos campos
# MIGRACIÓN NO-OP: Las columnas ya fueron creadas manualmente en Supabase via SQL
# Esta migración solo registra el estado en Django sin ejecutar cambios

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def noop_forward(apps, schema_editor):
    """
    No-op: Las columnas ya existen en producción (Supabase).
    Esta función existe solo para registrar la migración como aplicada.
    """
    pass


def noop_reverse(apps, schema_editor):
    """No-op reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lote_centro_fill'),
    ]

    operations = [
        # Operación vacía - todo el schema ya existe en producción
        migrations.RunPython(noop_forward, noop_reverse),
    ]


# NOTA: Esta migración es intencionalmente vacía porque:
# - Las tablas configuracion_sistema, hojas_recoleccion, detalle_hojas_recoleccion ya existen
# - Las columnas documento_nombre, documento_pdf en lotes ya existen
# - Las columnas lugar_entrega, fecha_recibido, observaciones_recepcion, usuario_recibe_id en requisiciones ya existen
# - La columna lugar_entrega en movimientos ya existe
# - La columna adscripcion en users ya existe
# Todo fue creado via SQL directo en Supabase el 2025-12-01
