# Generated by Django 5.2.8 on 2025-12-01 - Etapa 3 nuevos campos
# Migración manual para sincronizar modelos existentes y agregar nuevos campos

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lote_centro_fill'),
    ]

    operations = [
        # === Crear ConfiguracionSistema (registro en migraciones aunque tabla existe) ===
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Sistema de Farmacia Penitenciaria', help_text='Nombre que aparece en el header del sistema', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo del sistema (opcional)', null=True)),
                ('logo_header', models.ImageField(blank=True, help_text='Logo para el header de la interfaz (PNG/JPG, max 500KB)', null=True, upload_to='configuracion/logos/')),
                ('logo_pdf', models.ImageField(blank=True, help_text='Logo o fondo institucional para PDFs (PNG, recomendado 800x1200px)', null=True, upload_to='configuracion/logos/')),
                ('nombre_institucion', models.CharField(default='Secretaría de Seguridad', help_text='Nombre de la institución para reportes', max_length=200)),
                ('subtitulo_institucion', models.CharField(default='Dirección General de Prevención y Reinserción Social', help_text='Subtítulo de la institución para reportes', max_length=200)),
                ('color_primario', models.CharField(default='#1976D2', max_length=7)),
                ('color_primario_hover', models.CharField(default='#1565C0', max_length=7)),
                ('color_secundario', models.CharField(default='#424242', max_length=7)),
                ('color_acento', models.CharField(default='#FF5722', max_length=7)),
                ('color_fondo', models.CharField(default='#F5F5F5', max_length=7)),
                ('color_fondo_sidebar', models.CharField(default='#263238', max_length=7)),
                ('color_fondo_header', models.CharField(default='#1976D2', max_length=7)),
                ('color_fondo_card', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_texto', models.CharField(default='#212121', max_length=7)),
                ('color_texto_secundario', models.CharField(default='#757575', max_length=7)),
                ('color_texto_sidebar', models.CharField(default='#ECEFF1', max_length=7)),
                ('color_texto_header', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_exito', models.CharField(default='#4CAF50', max_length=7)),
                ('color_advertencia', models.CharField(default='#FF9800', max_length=7)),
                ('color_error', models.CharField(default='#F44336', max_length=7)),
                ('color_info', models.CharField(default='#2196F3', max_length=7)),
                ('tema_activo', models.CharField(default='default', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_sistema',
            },
        ),
        
        # === Crear HojaRecoleccion ===
        migrations.CreateModel(
            name='HojaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_hoja', models.CharField(max_length=50, unique=True)),
                ('hash_contenido', models.CharField(max_length=64)),
                ('contenido_json', models.JSONField(default=dict)),
                ('estado', models.CharField(default='generada', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('veces_impresa', models.PositiveIntegerField(default=0)),
                ('veces_descargada', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('requisicion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hoja_recoleccion', to='core.requisicion')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_generadas', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hojas_recoleccion',
                'ordering': ['-fecha_generacion'],
            },
        ),
        
        # === Crear DetalleHojaRecoleccion ===
        migrations.CreateModel(
            name='DetalleHojaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_autorizada', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_entregada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('hoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.hojarecoleccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('lote_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote')),
            ],
            options={
                'db_table': 'detalle_hojas_recoleccion',
                'unique_together': {('hoja', 'producto')},
            },
        ),
        
        # === Nuevos campos para Lote ===
        migrations.AddField(
            model_name='lote',
            name='documento_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lote',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lotes/documentos/%Y/%m/'),
        ),
        
        # === Nuevos campos para Movimiento ===
        migrations.AddField(
            model_name='movimiento',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=300),
        ),
        
        # === Nuevos campos para Requisicion ===
        migrations.AddField(
            model_name='requisicion',
            name='fecha_recibido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='observaciones_recepcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        
        # === Nuevo campo para User ===
        migrations.AddField(
            model_name='user',
            name='adscripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        
        # === Actualizar estado de requisicion ===
        migrations.AlterField(
            model_name='requisicion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('autorizada', 'Autorizada'), ('parcial', 'Parcialmente Autorizada'), ('rechazada', 'Rechazada'), ('surtida', 'Surtida'), ('recibida', 'Recibida por Centro'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
