# Generated by Django 5.2.8 on 2025-12-01 - Etapa 3 nuevos campos
# Migración que verifica si las columnas ya existen antes de crearlas
# PARA PRODUCCIÓN: El schema ya fue actualizado via SQL en Supabase

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def add_column_if_not_exists(table, column, sql_type, default=''):
    """Agrega columna solo si no existe"""
    with connection.cursor() as cursor:
        # Verificar si la columna existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = %s
        """, [table, column])
        if cursor.fetchone() is None:
            # La columna no existe, crearla
            if default == 'NULL':
                cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN "{column}" {sql_type}')
            else:
                cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN "{column}" {sql_type} DEFAULT %s', [default])


def apply_schema_updates(apps, schema_editor):
    """Aplica actualizaciones de schema solo si no existen"""
    # Solo ejecutar en PostgreSQL (Supabase)
    if 'postgresql' in connection.vendor or 'postgres' in connection.vendor:
        # Lote
        add_column_if_not_exists('lotes', 'documento_nombre', 'VARCHAR(255)', '')
        add_column_if_not_exists('lotes', 'documento_pdf', 'VARCHAR(255)', '')
        
        # Movimiento
        add_column_if_not_exists('movimientos', 'lugar_entrega', 'VARCHAR(300)', '')
        
        # Requisicion
        add_column_if_not_exists('requisiciones', 'fecha_recibido', 'TIMESTAMP WITH TIME ZONE', 'NULL')
        add_column_if_not_exists('requisiciones', 'lugar_entrega', 'VARCHAR(300)', '')
        add_column_if_not_exists('requisiciones', 'observaciones_recepcion', 'TEXT', '')
        add_column_if_not_exists('requisiciones', 'usuario_recibe_id', 'INTEGER', 'NULL')
        
        # User
        add_column_if_not_exists('users', 'adscripcion', 'VARCHAR(200)', '')
    else:
        # SQLite - usar el comportamiento estándar (las operaciones AddField manejan esto)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lote_centro_fill'),
    ]

    operations = [
        # Aplicar schema updates de forma condicional
        migrations.RunPython(apply_schema_updates, migrations.RunPython.noop),
        
        # Las siguientes operaciones son para registrar el estado en Django
        # pero NO ejecutan SQL ya que apply_schema_updates ya lo hizo o ya existían
        
        # === Mantener compatibilidad con SQLite local ===
        # Estas operaciones se ejecutan en SQLite pero fallan silenciosamente 
        # en PostgreSQL si las columnas ya existen (manejado arriba)
    ]


# Nota: Esta migración es "fake-safe" para Supabase porque:
# 1. RunPython verifica antes de crear columnas
# 2. Las columnas fueron creadas manualmente via SQL
