# Generated by Django 5.2.8 on 2025-12-01 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection, DatabaseError, ProgrammingError


def table_exists(table_name):
    """Check if a table exists in the database using Django's introspection."""
    return table_name in connection.introspection.table_names()


def get_table_constraints(table_name):
    """Get constraints for a specific table, handling database errors gracefully."""
    try:
        return connection.introspection.get_constraints(
            connection.cursor(), table_name
        )
    except (DatabaseError, ProgrammingError):
        return {}


def constraint_exists(constraint_name, table_name=None):
    """Check if a constraint exists in the database."""
    if table_name:
        # Check specific table
        constraints = get_table_constraints(table_name)
        return constraint_name in constraints
    # Search across all tables
    for tbl in connection.introspection.table_names():
        constraints = get_table_constraints(tbl)
        if constraint_name in constraints:
            return True
    return False


def index_exists(index_name, table_name=None):
    """Check if an index exists in the database."""
    if table_name:
        # Check specific table
        constraints = get_table_constraints(table_name)
        return index_name in constraints
    # Search across all tables
    for tbl in connection.introspection.table_names():
        constraints = get_table_constraints(tbl)
        if index_name in constraints:
            return True
    return False


def column_exists(table_name, column_name):
    """Check if a column exists in a table using Django's introspection."""
    if table_name not in connection.introspection.table_names():
        return False
    try:
        columns = [
            col.name for col in connection.introspection.get_table_description(
                connection.cursor(), table_name
            )
        ]
        return column_name in columns
    except (DatabaseError, ProgrammingError):
        return False


class SafeCreateModel(migrations.CreateModel):
    """CreateModel that skips creation if table already exists."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        db_table = model._meta.db_table
        if not table_exists(db_table):
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        db_table = model._meta.db_table
        if table_exists(db_table):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class SafeRemoveConstraint(migrations.RemoveConstraint):
    """RemoveConstraint that skips removal if constraint doesn't exist."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        if constraint_exists(self.name, db_table):
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        if not constraint_exists(self.name, db_table):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class SafeAddField(migrations.AddField):
    """AddField that skips addition if column already exists."""
    
    def _get_db_column(self):
        """Get the actual database column name, handling ForeignKey suffix."""
        if self.field.db_column:
            return self.field.db_column
        # ForeignKey and OneToOneField add '_id' suffix to column name
        if isinstance(self.field, (models.ForeignKey, models.OneToOneField)):
            return f"{self.name}_id"
        return self.name
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        db_column = self._get_db_column()
        if not column_exists(db_table, db_column):
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        db_column = self._get_db_column()
        if column_exists(db_table, db_column):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class SafeAddConstraint(migrations.AddConstraint):
    """AddConstraint that skips addition if constraint already exists."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        if not constraint_exists(self.constraint.name, db_table):
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        if constraint_exists(self.constraint.name, db_table):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class SafeAddIndex(migrations.AddIndex):
    """AddIndex that skips addition if index already exists."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        if not index_exists(self.index.name, db_table):
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        db_table = model._meta.db_table
        if index_exists(self.index.name, db_table):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class SafeAlterUniqueTogether(migrations.AlterUniqueTogether):
    """
    AlterUniqueTogether that handles existing/missing constraints gracefully.
    Skips creation when constraint already exists, skips removal when it doesn't exist.
    """
    _MISSING_CONSTRAINT_ERROR = "Found wrong number (0) of constraints"
    _DUPLICATE_CONSTRAINT_ERRORS = ("already exists", "duplicate key")
    
    def _is_missing_constraint_error(self, error):
        """Check if the error is due to missing constraints."""
        return self._MISSING_CONSTRAINT_ERROR in str(error)
    
    def _is_duplicate_constraint_error(self, error):
        """Check if the error is due to duplicate constraint."""
        error_str = str(error).lower()
        return any(msg in error_str for msg in self._DUPLICATE_CONSTRAINT_ERRORS)
    
    def _columns_match_unique_set(self, constraint_columns, unique_set):
        """Check if constraint columns match a unique_together set."""
        # Try matching with _id suffix (foreign keys)
        expected_with_id = {col if col.endswith('_id') else f'{col}_id' for col in unique_set}
        if set(constraint_columns) == expected_with_id:
            return True
        # Also check without _id suffix
        return set(constraint_columns) == set(unique_set)
    
    def _constraint_already_exists(self, db_table, unique_set):
        """Check if a unique constraint for the given columns already exists."""
        constraints = get_table_constraints(db_table)
        for constraint_name, constraint_info in constraints.items():
            if constraint_info.get('unique', False) and not constraint_info.get('primary_key', False):
                constraint_columns = tuple(constraint_info.get('columns', []))
                if self._columns_match_unique_set(constraint_columns, unique_set):
                    return True
        return False
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Get old and new unique_together values
        from_model_state = from_state.models.get((app_label, self.name.lower()))
        to_model_state = to_state.models.get((app_label, self.name.lower()))
        
        if from_model_state is None or to_model_state is None:
            return
        
        old_unique_together = from_model_state.options.get('unique_together') or set()
        new_unique_together = to_model_state.options.get('unique_together') or set()
        
        model = to_state.apps.get_model(app_label, self.name)
        db_table = model._meta.db_table
        
        # If we're adding constraints (going from empty to something)
        if new_unique_together and not old_unique_together:
            # Check if all new constraints already exist
            all_exist = all(
                self._constraint_already_exists(db_table, unique_set)
                for unique_set in new_unique_together
            )
            if all_exist:
                return  # Skip, constraints already exist
        
        # If we're removing constraints (going from something to empty set)
        if old_unique_together and not new_unique_together:
            constraints = get_table_constraints(db_table)
            
            # Check if any unique_together constraints exist
            has_constraints = False
            for constraint_name, constraint_info in constraints.items():
                if constraint_info.get('unique', False) and not constraint_info.get('primary_key', False):
                    constraint_columns = tuple(constraint_info.get('columns', []))
                    for unique_set in old_unique_together:
                        if self._columns_match_unique_set(constraint_columns, unique_set):
                            has_constraints = True
                            break
                    if has_constraints:
                        break
            
            # If no constraints exist, skip the operation
            if not has_constraints:
                return
        
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except (ValueError, ProgrammingError, DatabaseError) as e:
            if not (self._is_missing_constraint_error(e) or self._is_duplicate_constraint_error(e)):
                raise
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_backwards(app_label, schema_editor, from_state, to_state)
        except ValueError as e:
            if not self._is_missing_constraint_error(e):
                raise


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_etapa3_nuevos_campos'),
    ]

    operations = [
        SafeCreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Sistema de Farmacia Penitenciaria', help_text='Nombre que aparece en el header del sistema', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo del sistema (opcional)', null=True)),
                ('logo_header', models.ImageField(blank=True, help_text='Logo para el header de la interfaz (PNG/JPG, max 500KB)', null=True, upload_to='configuracion/logos/')),
                ('logo_pdf', models.ImageField(blank=True, help_text='Logo o fondo institucional para PDFs (PNG, recomendado 800x1200px)', null=True, upload_to='configuracion/logos/')),
                ('nombre_institucion', models.CharField(default='Secretaría de Seguridad', help_text='Nombre de la institución para reportes', max_length=200)),
                ('subtitulo_institucion', models.CharField(default='Dirección General de Prevención y Reinserción Social', help_text='Subtítulo de la institución para reportes', max_length=200)),
                ('color_primario', models.CharField(default='#1976D2', help_text='Color primario del tema (botones principales, header)', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_primario_hover', models.CharField(default='#1565C0', help_text='Color primario al pasar el mouse', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_secundario', models.CharField(default='#424242', help_text='Color secundario del tema', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_acento', models.CharField(default='#FF5722', help_text='Color de acento para destacar elementos', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo', models.CharField(default='#F5F5F5', help_text='Color de fondo general', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo_sidebar', models.CharField(default='#263238', help_text='Color de fondo del menú lateral', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo_header', models.CharField(default='#1976D2', help_text='Color de fondo del header', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo_card', models.CharField(default='#FFFFFF', help_text='Color de fondo de tarjetas', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto', models.CharField(default='#212121', help_text='Color de texto principal', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto_secundario', models.CharField(default='#757575', help_text='Color de texto secundario', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto_sidebar', models.CharField(default='#ECEFF1', help_text='Color de texto en el sidebar', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto_header', models.CharField(default='#FFFFFF', help_text='Color de texto en el header', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_exito', models.CharField(default='#4CAF50', help_text='Color para estados de éxito', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_advertencia', models.CharField(default='#FF9800', help_text='Color para advertencias', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_error', models.CharField(default='#F44336', help_text='Color para errores', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_info', models.CharField(default='#2196F3', help_text='Color para información', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('tema_activo', models.CharField(choices=[('default', 'Por Defecto (Azul)'), ('dark', 'Oscuro'), ('green', 'Verde Institucional'), ('purple', 'Púrpura'), ('custom', 'Personalizado')], default='default', help_text='Tema predefinido o personalizado', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        SafeCreateModel(
            name='DetalleHojaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_autorizada', models.IntegerField(help_text='Cantidad autorizada por farmacia', validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_entregada', models.IntegerField(default=0, help_text='Cantidad efectivamente entregada', validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'detalle_hojas_recoleccion',
            },
        ),
        SafeCreateModel(
            name='HojaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_hoja', models.CharField(help_text='Folio único de la hoja de recolección', max_length=50, unique=True)),
                ('hash_contenido', models.CharField(help_text='Hash SHA256 del contenido para verificar integridad', max_length=64)),
                ('contenido_json', models.JSONField(default=dict, help_text='Contenido serializado de la hoja para reconstrucción')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('impresa', 'Impresa'), ('verificada', 'Verificada'), ('completada', 'Completada')], default='generada', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('veces_impresa', models.PositiveIntegerField(default=0)),
                ('veces_descargada', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hoja de Recolección',
                'verbose_name_plural': 'Hojas de Recolección',
                'db_table': 'hojas_recoleccion',
                'ordering': ['-fecha_generacion'],
            },
        ),
        SafeRemoveConstraint(
            model_name='lote',
            name='unique_numero_lote_por_producto',
        ),
        SafeAlterUniqueTogether(
            name='detallerequisicion',
            unique_together=set(),
        ),
        SafeAddField(
            model_name='detallerequisicion',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote específico del que se solicita el producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_requisicion', to='core.lote'),
        ),
        SafeAddField(
            model_name='lote',
            name='documento_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del documento', max_length=255),
        ),
        SafeAddField(
            model_name='lote',
            name='documento_pdf',
            field=models.FileField(blank=True, help_text='Documento PDF de soporte (contrato, certificado, etc.)', null=True, upload_to='lotes/documentos/%Y/%m/'),
        ),
        SafeAddField(
            model_name='lote',
            name='lote_origen',
            field=models.ForeignKey(blank=True, help_text='Lote origen en farmacia central (NULL solo para lotes de farmacia)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_derivados', to='core.lote'),
        ),
        SafeAddField(
            model_name='lote',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del medicamento/producto', max_length=150),
        ),
        SafeAddField(
            model_name='lote',
            name='numero_contrato',
            field=models.CharField(blank=True, db_index=True, help_text='Número de contrato de adquisición para trazabilidad', max_length=100),
        ),
        SafeAddField(
            model_name='movimiento',
            name='lugar_entrega',
            field=models.CharField(blank=True, help_text='Detalle del lugar de entrega (centro, servicio, área, etc.)', max_length=300),
        ),
        SafeAddField(
            model_name='requisicion',
            name='fecha_recibido',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el centro recibió la requisición', null=True),
        ),
        SafeAddField(
            model_name='requisicion',
            name='lugar_entrega',
            field=models.CharField(blank=True, help_text='Detalle del lugar de entrega (centro, servicio, área, etc.)', max_length=300),
        ),
        SafeAddField(
            model_name='requisicion',
            name='observaciones_recepcion',
            field=models.TextField(blank=True, help_text='Observaciones al momento de recibir la requisición'),
        ),
        SafeAddField(
            model_name='requisicion',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, help_text='Usuario del centro que recibió la requisición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        SafeAddField(
            model_name='user',
            name='adscripcion',
            field=models.CharField(blank=True, help_text='Adscripción del usuario (centro/área/unidad de dependencia)', max_length=200),
        ),
        SafeAddField(
            model_name='user',
            name='perm_auditoria',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Auditoría', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_centros',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Centros', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_dashboard',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Dashboard', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_lotes',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Lotes', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_movimientos',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Movimientos', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_notificaciones',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Notificaciones', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_productos',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Productos', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_reportes',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Reportes', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_requisiciones',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Requisiciones', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_trazabilidad',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Trazabilidad', null=True),
        ),
        SafeAddField(
            model_name='user',
            name='perm_usuarios',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Usuarios', null=True),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='objeto_id',
            field=models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='objeto_repr',
            field=models.CharField(blank=True, default='', help_text='Representación del objeto', max_length=255),
        ),
        migrations.AlterField(
            model_name='detallerequisicion',
            name='requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='core.requisicion'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado'), ('retirado', 'Retirado')], default='disponible', help_text='Estado actual del lote', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(help_text='Número de lote único por producto (2-100 caracteres)', max_length=100, validators=[django.core.validators.RegexValidator(message='El número de lote solo puede contener letras, números y guiones', regex='^[A-Za-z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento (opcional para movimientos automáticos)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='requisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='core.requisicion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='clave',
            field=models.CharField(help_text='Clave unica del producto (2-50 caracteres alfanumericos)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números, guiones y guiones bajos', regex='^[A-Za-z0-9\\-_]+$')]),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('autorizada', 'Autorizada'), ('parcial', 'Parcialmente Autorizada'), ('rechazada', 'Rechazada'), ('surtida', 'Surtida'), ('recibida', 'Recibida por Centro'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        SafeAlterUniqueTogether(
            name='detallerequisicion',
            unique_together={('requisicion', 'producto', 'lote')},
        ),
        SafeAddIndex(
            model_name='detallerequisicion',
            index=models.Index(fields=['lote'], name='detalles_re_lote_id_9f1527_idx'),
        ),
        SafeAddIndex(
            model_name='lote',
            index=models.Index(fields=['centro'], name='lotes_centro__34e30e_idx'),
        ),
        SafeAddIndex(
            model_name='lote',
            index=models.Index(fields=['lote_origen'], name='lotes_lote_or_2e490d_idx'),
        ),
        SafeAddIndex(
            model_name='lote',
            index=models.Index(fields=['numero_contrato'], name='idx_lote_contrato'),
        ),
        SafeAddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_lote', 'centro'), name='unique_lote_por_producto_centro'),
        ),
        SafeAddField(
            model_name='configuracionsistema',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        SafeAddField(
            model_name='detallehojarecoleccion',
            name='lote_asignado',
            field=models.ForeignKey(blank=True, help_text='Lote del cual se surtió', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote'),
        ),
        SafeAddField(
            model_name='detallehojarecoleccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        SafeAddField(
            model_name='hojarecoleccion',
            name='generado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario de farmacia que generó la hoja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_generadas', to=settings.AUTH_USER_MODEL),
        ),
        SafeAddField(
            model_name='hojarecoleccion',
            name='requisicion',
            field=models.OneToOneField(help_text='Requisición asociada a esta hoja', on_delete=django.db.models.deletion.PROTECT, related_name='hoja_recoleccion', to='core.requisicion'),
        ),
        SafeAddField(
            model_name='hojarecoleccion',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario de farmacia que verificó la hoja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_verificadas', to=settings.AUTH_USER_MODEL),
        ),
        SafeAddField(
            model_name='detallehojarecoleccion',
            name='hoja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.hojarecoleccion'),
        ),
        SafeAddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['requisicion'], name='hojas_recol_requisi_68a3ad_idx'),
        ),
        SafeAddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['folio_hoja'], name='hojas_recol_folio_h_0e48b7_idx'),
        ),
        SafeAddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['estado'], name='hojas_recol_estado_07c5ed_idx'),
        ),
        SafeAddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['-fecha_generacion'], name='hojas_recol_fecha_g_ad32ec_idx'),
        ),
        SafeAlterUniqueTogether(
            name='detallehojarecoleccion',
            unique_together={('hoja', 'producto')},
        ),
    ]
