# Generated by Django 5.2.8 on 2025-11-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fix_auditorialog_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_auditoria',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Auditoría', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_centros',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Centros', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_dashboard',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Dashboard', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_lotes',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Lotes', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_movimientos',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Movimientos', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_notificaciones',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Notificaciones', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_productos',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Productos', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_reportes',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Reportes', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_requisiciones',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Requisiciones', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_trazabilidad',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Trazabilidad', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_usuarios',
            field=models.BooleanField(blank=True, help_text='Permiso para ver Usuarios', null=True),
        ),
    ]
