# Generated by Django 5.2.8 on 2025-12-03 20:09

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracionsistema_detallehojarecoleccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='color_acento',
            field=models.CharField(default='#BC955C', help_text='Color de acento para destacar elementos', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='color_fondo_header',
            field=models.CharField(default='#9F2241', help_text='Color de fondo del header', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='color_fondo_sidebar',
            field=models.CharField(default='#9F2241', help_text='Color de fondo del menú lateral', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='color_primario',
            field=models.CharField(default='#9F2241', help_text='Color primario del tema (botones principales, header)', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='color_primario_hover',
            field=models.CharField(default='#6B1839', help_text='Color primario al pasar el mouse', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='color_texto_sidebar',
            field=models.CharField(default='#FFFFFF', help_text='Color de texto en el sidebar', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='logo_header',
            field=models.ImageField(blank=True, help_text='Logo para el header de la interfaz (PNG/JPG, max 500KB)', null=True, upload_to='configuracion/logos/', validators=[core.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='logo_pdf',
            field=models.ImageField(blank=True, help_text='Logo o fondo institucional para PDFs (PNG, recomendado 800x1200px)', null=True, upload_to='configuracion/logos/', validators=[core.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tema_activo',
            field=models.CharField(choices=[('default', 'Por Defecto (Institucional)'), ('dark', 'Oscuro'), ('green', 'Verde Institucional'), ('purple', 'Púrpura'), ('custom', 'Personalizado')], default='default', help_text='Tema predefinido o personalizado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida', '-fecha_creacion'], name='idx_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', '-fecha_creacion'], name='idx_notif_user_date'),
        ),
    ]
