# Generated by Django 5.2.8 on 2025-11-26 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_detallerequisicion_requisicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Sistema de Farmacia Penitenciaria', help_text='Nombre que aparece en el header del sistema', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo del sistema (opcional)', null=True)),
                ('color_primario', models.CharField(default='#1976D2', help_text='Color primario del tema (botones principales, header)', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_primario_hover', models.CharField(default='#1565C0', help_text='Color primario al pasar el mouse', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_secundario', models.CharField(default='#424242', help_text='Color secundario del tema', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_acento', models.CharField(default='#FF5722', help_text='Color de acento para destacar elementos', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo', models.CharField(default='#F5F5F5', help_text='Color de fondo general', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo_sidebar', models.CharField(default='#263238', help_text='Color de fondo del menú lateral', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo_header', models.CharField(default='#1976D2', help_text='Color de fondo del header', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo_card', models.CharField(default='#FFFFFF', help_text='Color de fondo de tarjetas', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto', models.CharField(default='#212121', help_text='Color de texto principal', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto_secundario', models.CharField(default='#757575', help_text='Color de texto secundario', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto_sidebar', models.CharField(default='#ECEFF1', help_text='Color de texto en el sidebar', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto_header', models.CharField(default='#FFFFFF', help_text='Color de texto en el header', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_exito', models.CharField(default='#4CAF50', help_text='Color para estados de éxito', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_advertencia', models.CharField(default='#FF9800', help_text='Color para advertencias', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_error', models.CharField(default='#F44336', help_text='Color para errores', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_info', models.CharField(default='#2196F3', help_text='Color para información', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('tema_activo', models.CharField(choices=[('default', 'Por Defecto (Azul)'), ('dark', 'Oscuro'), ('green', 'Verde Institucional'), ('purple', 'Púrpura'), ('custom', 'Personalizado')], default='default', help_text='Tema predefinido o personalizado', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
