# Generated by Django 5.2.8 on 2025-12-03 22:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_notificacion_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tema Institucional', help_text='Nombre descriptivo del tema', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion del tema')),
                ('activo', models.BooleanField(default=True, help_text='Solo un tema puede estar activo a la vez')),
                ('es_tema_institucional', models.BooleanField(default=False, help_text='Indica si es el tema institucional por defecto')),
                ('logo_header', models.ImageField(blank=True, help_text='Logo principal mostrado en el header (max 500KB)', null=True, upload_to='tema/logos/', validators=[core.models.validate_logo_size])),
                ('logo_login', models.ImageField(blank=True, help_text='Logo para pantalla de login (max 500KB)', null=True, upload_to='tema/logos/', validators=[core.models.validate_logo_size])),
                ('logo_reportes', models.ImageField(blank=True, help_text='Logo para encabezado de reportes PDF (max 500KB)', null=True, upload_to='tema/logos/', validators=[core.models.validate_logo_size])),
                ('favicon', models.ImageField(blank=True, help_text='Favicon del sitio (ICO o PNG 32x32)', null=True, upload_to='tema/logos/')),
                ('imagen_fondo_login', models.ImageField(blank=True, help_text='Imagen de fondo para pantalla de login', null=True, upload_to='tema/imagenes/')),
                ('imagen_fondo_reportes', models.ImageField(blank=True, help_text='Imagen de fondo/marca de agua para reportes', null=True, upload_to='tema/imagenes/')),
                ('color_primario', models.CharField(default='#1e3a5f', help_text='Color primario (hex). Usado en header, botones principales', max_length=7)),
                ('color_primario_hover', models.CharField(default='#15293f', help_text='Color primario en hover', max_length=7)),
                ('color_secundario', models.CharField(default='#3b82f6', help_text='Color secundario/acento', max_length=7)),
                ('color_secundario_hover', models.CharField(default='#2563eb', help_text='Color secundario en hover', max_length=7)),
                ('color_exito', models.CharField(default='#10b981', help_text='Color para estados de exito (verde)', max_length=7)),
                ('color_error', models.CharField(default='#ef4444', help_text='Color para errores (rojo)', max_length=7)),
                ('color_advertencia', models.CharField(default='#f59e0b', help_text='Color para advertencias (amarillo/naranja)', max_length=7)),
                ('color_info', models.CharField(default='#3b82f6', help_text='Color para informacion (azul)', max_length=7)),
                ('color_fondo_principal', models.CharField(default='#f3f4f6', help_text='Color de fondo principal del layout', max_length=7)),
                ('color_fondo_tarjetas', models.CharField(default='#ffffff', help_text='Color de fondo de tarjetas y paneles', max_length=7)),
                ('color_fondo_sidebar', models.CharField(default='#1e3a5f', help_text='Color de fondo del sidebar/menu', max_length=7)),
                ('color_fondo_header', models.CharField(default='#1e3a5f', help_text='Color de fondo del header', max_length=7)),
                ('color_texto_principal', models.CharField(default='#1f2937', help_text='Color de texto principal', max_length=7)),
                ('color_texto_secundario', models.CharField(default='#6b7280', help_text='Color de texto secundario/muted', max_length=7)),
                ('color_texto_invertido', models.CharField(default='#ffffff', help_text='Color de texto sobre fondos oscuros', max_length=7)),
                ('color_texto_links', models.CharField(default='#3b82f6', help_text='Color de enlaces', max_length=7)),
                ('color_borde', models.CharField(default='#e5e7eb', help_text='Color de bordes por defecto', max_length=7)),
                ('color_borde_focus', models.CharField(default='#3b82f6', help_text='Color de borde en focus', max_length=7)),
                ('fuente_principal', models.CharField(choices=[('Inter', 'Inter (Sans-serif moderno)'), ('Roboto', 'Roboto (Sans-serif Google)'), ('Open Sans', 'Open Sans (Sans-serif legible)'), ('Lato', 'Lato (Sans-serif elegante)'), ('Montserrat', 'Montserrat (Sans-serif geometrico)'), ('Poppins', 'Poppins (Sans-serif redondeado)'), ('Source Sans Pro', 'Source Sans Pro (Adobe)'), ('Nunito', 'Nunito (Sans-serif suave)'), ('Arial', 'Arial (Sistema)'), ('Helvetica', 'Helvetica (Sistema)')], default='Inter', help_text='Familia tipografica principal', max_length=50)),
                ('fuente_titulos', models.CharField(choices=[('Inter', 'Inter (Sans-serif moderno)'), ('Roboto', 'Roboto (Sans-serif Google)'), ('Open Sans', 'Open Sans (Sans-serif legible)'), ('Lato', 'Lato (Sans-serif elegante)'), ('Montserrat', 'Montserrat (Sans-serif geometrico)'), ('Poppins', 'Poppins (Sans-serif redondeado)'), ('Source Sans Pro', 'Source Sans Pro (Adobe)'), ('Nunito', 'Nunito (Sans-serif suave)'), ('Arial', 'Arial (Sistema)'), ('Helvetica', 'Helvetica (Sistema)')], default='Inter', help_text='Familia tipografica para titulos', max_length=50)),
                ('tamano_h1', models.CharField(default='2rem', help_text='Tamano de titulos H1', max_length=10)),
                ('tamano_h2', models.CharField(default='1.5rem', help_text='Tamano de titulos H2', max_length=10)),
                ('tamano_h3', models.CharField(default='1.25rem', help_text='Tamano de titulos H3', max_length=10)),
                ('tamano_texto_base', models.CharField(default='1rem', help_text='Tamano de texto base/parrafos', max_length=10)),
                ('tamano_texto_pequeno', models.CharField(default='0.875rem', help_text='Tamano de texto pequeno', max_length=10)),
                ('tamano_etiquetas', models.CharField(default='0.875rem', help_text='Tamano de etiquetas de formulario', max_length=10)),
                ('tamano_botones', models.CharField(default='0.875rem', help_text='Tamano de texto en botones', max_length=10)),
                ('peso_titulos', models.CharField(default='700', help_text='Peso de fuente para titulos (400-900)', max_length=10)),
                ('peso_texto_normal', models.CharField(default='400', help_text='Peso de fuente para texto normal', max_length=10)),
                ('peso_botones', models.CharField(default='600', help_text='Peso de fuente para botones', max_length=10)),
                ('reporte_ano_visible', models.CharField(default='2025', help_text='Ano que aparece en los reportes', max_length=10)),
                ('reporte_titulo_institucion', models.CharField(default='Sistema de Farmacia Penitenciaria', help_text='Titulo de la institucion en reportes', max_length=200)),
                ('reporte_subtitulo', models.CharField(blank=True, default='Control de Inventario y Distribucion', help_text='Subtitulo en reportes', max_length=200)),
                ('reporte_pie_pagina', models.CharField(blank=True, default='Documento generado por el Sistema de Farmacia Penitenciaria', help_text='Texto del pie de pagina en reportes', max_length=300)),
                ('reporte_color_encabezado', models.CharField(default='#1e3a5f', help_text='Color de fondo del encabezado de tablas en reportes', max_length=7)),
                ('reporte_color_texto_encabezado', models.CharField(default='#ffffff', help_text='Color de texto en encabezado de tablas', max_length=7)),
                ('reporte_color_filas_alternas', models.CharField(default='#f9fafb', help_text='Color de filas alternas en tablas', max_length=7)),
                ('border_radius_base', models.CharField(default='0.5rem', help_text='Radio de borde base para elementos', max_length=10)),
                ('border_radius_botones', models.CharField(default='0.375rem', help_text='Radio de borde para botones', max_length=10)),
                ('shadow_base', models.CharField(default='0 1px 3px 0 rgba(0, 0, 0, 0.1)', help_text='Sombra base para tarjetas', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema Global',
                'verbose_name_plural': 'Temas Globales',
                'db_table': 'tema_global',
            },
        ),
    ]
