# Generated by Django 5.2.8 on 2025-11-26 20:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuracion_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_hoja', models.CharField(help_text='Folio único de la hoja de recolección', max_length=50, unique=True)),
                ('hash_contenido', models.CharField(help_text='Hash SHA256 del contenido para verificar integridad', max_length=64)),
                ('contenido_json', models.JSONField(default=dict, help_text='Contenido serializado de la hoja para reconstrucción')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('impresa', 'Impresa'), ('verificada', 'Verificada'), ('completada', 'Completada')], default='generada', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('veces_impresa', models.PositiveIntegerField(default=0)),
                ('veces_descargada', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('generado_por', models.ForeignKey(blank=True, help_text='Usuario de farmacia que generó la hoja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_generadas', to=settings.AUTH_USER_MODEL)),
                ('requisicion', models.OneToOneField(help_text='Requisición asociada a esta hoja', on_delete=django.db.models.deletion.PROTECT, related_name='hoja_recoleccion', to='core.requisicion')),
                ('verificado_por', models.ForeignKey(blank=True, help_text='Usuario de farmacia que verificó la hoja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoja de Recolección',
                'verbose_name_plural': 'Hojas de Recolección',
                'db_table': 'hojas_recoleccion',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleHojaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_autorizada', models.IntegerField(help_text='Cantidad autorizada por farmacia', validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_entregada', models.IntegerField(default=0, help_text='Cantidad efectivamente entregada', validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('lote_asignado', models.ForeignKey(blank=True, help_text='Lote del cual se surtió', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('hoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.hojarecoleccion')),
            ],
            options={
                'db_table': 'detalle_hojas_recoleccion',
            },
        ),
        migrations.AddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['requisicion'], name='hojas_recol_requisi_68a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['folio_hoja'], name='hojas_recol_folio_h_0e48b7_idx'),
        ),
        migrations.AddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['estado'], name='hojas_recol_estado_07c5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='hojarecoleccion',
            index=models.Index(fields=['-fecha_generacion'], name='hojas_recol_fecha_g_ad32ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallehojarecoleccion',
            unique_together={('hoja', 'producto')},
        ),
    ]
