# Generated by Django 5.2.8 on 2025-11-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_movimiento_usuario_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallerequisicion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detallerequisicion',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote específico del que se solicita el producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_requisicion', to='core.lote'),
        ),
        migrations.AlterUniqueTogether(
            name='detallerequisicion',
            unique_together={('requisicion', 'producto', 'lote')},
        ),
        migrations.AddIndex(
            model_name='detallerequisicion',
            index=models.Index(fields=['lote'], name='detalles_re_lote_id_9f1527_idx'),
        ),
    ]
