# Generated by Django 5.2.8 on 2025-12-04 20:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_iss019_constraints_iss032_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lote',
            name='documento_pdf',
            field=models.FileField(blank=True, help_text='Documento PDF de soporte (contrato, certificado, etc.) - Máximo 10MB', null=True, upload_to=core.models.pdf_upload_path, validators=[core.models.validate_pdf_file]),
        ),
    ]
