# Generated by Django 5.2.8 on 2025-12-04 21:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_iss005_007_009_auditoria_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSurtido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad surtida de este lote específico', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_surtido', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de Surtido',
                'verbose_name_plural': 'Detalles de Surtido',
                'db_table': 'detalle_surtidos',
                'ordering': ['-fecha_surtido'],
            },
        ),
        migrations.AddConstraint(
            model_name='detallerequisicion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_surtida__lte', models.F('cantidad_autorizada')), ('cantidad_autorizada', 0), _connector='OR'), name='ck_detalle_surtida_no_excede_autorizada', violation_error_message='La cantidad surtida no puede exceder la cantidad autorizada'),
        ),
        migrations.AddConstraint(
            model_name='detallerequisicion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_autorizada__lte', models.F('cantidad_solicitada'))), name='ck_detalle_autorizada_no_excede_solicitada', violation_error_message='La cantidad autorizada no puede exceder la cantidad solicitada'),
        ),
        migrations.AddConstraint(
            model_name='detallerequisicion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_autorizada__gte', 0), ('cantidad_surtida__gte', 0)), name='ck_detalle_cantidades_no_negativas', violation_error_message='Las cantidades no pueden ser negativas'),
        ),
        migrations.AddField(
            model_name='detallesurtido',
            name='detalle_requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surtidos', to='core.detallerequisicion'),
        ),
        migrations.AddField(
            model_name='detallesurtido',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_surtidos', to='core.lote'),
        ),
        migrations.AddField(
            model_name='detallesurtido',
            name='movimiento',
            field=models.ForeignKey(blank=True, help_text='Movimiento de salida asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_surtidos', to='core.movimiento'),
        ),
        migrations.AddField(
            model_name='detallesurtido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='detallesurtido',
            index=models.Index(fields=['detalle_requisicion', 'lote'], name='detalle_sur_detalle_b8098c_idx'),
        ),
        migrations.AddIndex(
            model_name='detallesurtido',
            index=models.Index(fields=['lote', '-fecha_surtido'], name='detalle_sur_lote_id_2762dd_idx'),
        ),
    ]
