# Generated by Django 5.2.8 on 2025-11-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_lote_to_detallerequisicion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lote',
            name='unique_numero_lote_por_producto',
        ),
        migrations.AddField(
            model_name='lote',
            name='lote_origen',
            field=models.ForeignKey(blank=True, help_text='Lote origen en farmacia central (NULL solo para lotes de farmacia)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_derivados', to='core.lote'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['centro'], name='lotes_centro__34e30e_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['lote_origen'], name='lotes_lote_or_2e490d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_lote', 'centro'), name='unique_lote_por_producto_centro'),
        ),
    ]
