# Generated by Django 5.2.8 on 2025-11-28 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_lote_origen_vinculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del medicamento/producto', max_length=150),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_contrato',
            field=models.CharField(blank=True, db_index=True, help_text='Número de contrato de adquisición para trazabilidad', max_length=100),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado'), ('retirado', 'Retirado')], default='disponible', help_text='Estado actual del lote', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(help_text='Número de lote único por producto (2-100 caracteres)', max_length=100, validators=[django.core.validators.RegexValidator(message='El número de lote solo puede contener letras, números y guiones', regex='^[A-Za-z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='clave',
            field=models.CharField(help_text='Clave unica del producto (2-50 caracteres alfanumericos)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números, guiones y guiones bajos', regex='^[A-Za-z0-9\\-_]+$')]),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['numero_contrato'], name='idx_lote_contrato'),
        ),
    ]
