# Generated by Django 5.2.8 on 2025-12-04 22:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_iss002_detalle_surtido_iss003_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequisicion',
            name='cantidad_reservada',
            field=models.IntegerField(default=0, help_text='Cantidad reservada al momento de autorizar (para garantizar stock)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detallerequisicion',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que se realizó la reserva de stock', null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero_contrato',
            field=models.CharField(blank=True, db_index=True, help_text='Número de contrato de adquisición para trazabilidad (legacy)', max_length=100),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(db_index=True, help_text='Número único de contrato', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del contrato')),
                ('proveedor', models.CharField(help_text='Nombre del proveedor', max_length=200)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de vigencia')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de vigencia')),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo del contrato', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True, help_text='Si el contrato está vigente y puede usarse')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales del contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato de adquisición (nuevo modelo con límites y vigencia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='core.contrato'),
        ),
        migrations.CreateModel(
            name='ContratoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima', models.IntegerField(help_text='Cantidad máxima permitida bajo este contrato', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario acordado en el contrato', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.contrato')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_productos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Producto en Contrato',
                'verbose_name_plural': 'Productos en Contrato',
                'db_table': 'contratos_productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.IntegerField(help_text='Cantidad efectivamente recibida de este lote', validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_esperada', models.IntegerField(default=0, help_text='Cantidad que se esperaba recibir (según surtido)', validators=[django.core.validators.MinValueValidator(0)])),
                ('tiene_discrepancia', models.BooleanField(default=False, help_text='Si la cantidad recibida difiere de la esperada')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre el estado del producto recibido')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('detalle_requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='core.detallerequisicion')),
                ('lote_centro', models.ForeignKey(help_text='Lote creado en el centro al recibir', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recepcion', to='core.lote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepción',
                'db_table': 'detalle_recepciones',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['numero_contrato'], name='contratos_numero__6db3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['proveedor'], name='contratos_proveed_f50956_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='contratos_fecha_i_d1a003_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['activo'], name='contratos_activo_d7765d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contratoproducto',
            unique_together={('contrato', 'producto')},
        ),
        migrations.AddIndex(
            model_name='detallerecepcion',
            index=models.Index(fields=['detalle_requisicion', 'lote_centro'], name='detalle_rec_detalle_642eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='detallerecepcion',
            index=models.Index(fields=['lote_centro', '-fecha_recepcion'], name='detalle_rec_lote_ce_359e04_idx'),
        ),
        migrations.AddIndex(
            model_name='detallerecepcion',
            index=models.Index(fields=['tiene_discrepancia'], name='detalle_rec_tiene_d_32184a_idx'),
        ),
    ]
