# Generated by Django 5.2.8 on 2025-12-05 20:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fix_tema_colores_institucionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (JPG, PNG - máximo 2MB)', null=True, upload_to=core.models.producto_imagen_path, validators=[core.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_firma_recepcion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se firmó la recepción', null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_firma_surtido',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se firmó el surtido', null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='foto_firma_recepcion',
            field=models.ImageField(blank=True, help_text='Foto de la firma al momento de recibir la requisición (máximo 2MB)', null=True, upload_to=core.models.requisicion_firma_path, validators=[core.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='foto_firma_surtido',
            field=models.ImageField(blank=True, help_text='Foto de la firma al momento de surtir la requisición (máximo 2MB)', null=True, upload_to=core.models.requisicion_firma_path, validators=[core.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario_firma_recepcion',
            field=models.ForeignKey(blank=True, help_text='Usuario que firmó la recepción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_firmadas_recepcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario_firma_surtido',
            field=models.ForeignKey(blank=True, help_text='Usuario que firmó el surtido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_firmadas_surtido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_borde_focus',
            field=models.CharField(default='#9F2241', help_text='Color de borde en focus', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_fondo_header',
            field=models.CharField(default='#9F2241', help_text='Color de fondo del header', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_fondo_sidebar',
            field=models.CharField(default='#9F2241', help_text='Color de fondo del sidebar/menu', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_primario',
            field=models.CharField(default='#9F2241', help_text='Color primario (hex). Usado en header, botones principales', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_primario_hover',
            field=models.CharField(default='#6B1839', help_text='Color primario en hover', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_secundario',
            field=models.CharField(default='#424242', help_text='Color secundario/acento', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_secundario_hover',
            field=models.CharField(default='#2E2E2E', help_text='Color secundario en hover', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='color_texto_links',
            field=models.CharField(default='#9F2241', help_text='Color de enlaces', max_length=7),
        ),
        migrations.AlterField(
            model_name='temaglobal',
            name='reporte_color_encabezado',
            field=models.CharField(default='#9F2241', help_text='Color de fondo del encabezado de tablas en reportes', max_length=7),
        ),
    ]
