# Generated by Django 5.2.8 on 2025-12-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_producto_imagen_requisicion_firmas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False, 'ordering': ['-fecha_inicio'], 'verbose_name': 'Contrato (Legacy)', 'verbose_name_plural': 'Contratos (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='contratoproducto',
            options={'managed': False, 'verbose_name': 'Producto en Contrato (Legacy)', 'verbose_name_plural': 'Productos en Contrato (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='detallerecepcion',
            options={'managed': False, 'verbose_name': 'Detalle de Recepción (Legacy)', 'verbose_name_plural': 'Detalles de Recepción (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='detallesurtido',
            options={'managed': False, 'verbose_name': 'Detalle de Surtido', 'verbose_name_plural': 'Detalles de Surtido'},
        ),
        migrations.RemoveField(
            model_name='lote',
            name='contrato',
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero_contrato',
            field=models.CharField(blank=True, db_index=True, help_text='Número de contrato de adquisición para trazabilidad', max_length=100),
        ),
    ]
