# Generated by Django 5.2.8 on 2026-03-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_fix_detallehoja_requisicion_do_nothing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorialogs',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
    ]
